### ISSUE TITLE
Some errors in 64 platform "‘BigInt::BigInt(uint64_t)’ cannot be overloaded"

### ISSUE THREAD

**Issue by luzhengfei** [JorjBauer/lua-bigint#1]
I make some change in Bigint.h
#define BIGINT_PRIMITIVE_SIZE 64 "old version is 32"

but get some error?

OS：Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
g++ -O2 -fPIC -I/usr/include -lstdc++ -c BigInt.cpp -o BigInt.o -DVERSION="1.02"

BigInt.h:64: error: ‘BigInt::BigInt(uint64_t)’ cannot be overloaded
BigInt.h:59: error: with ‘BigInt::BigInt(long unsigned int)’
BigInt.cpp:98: error: redefinition of ‘BigInt::BigInt(uint64_t)’
BigInt.cpp:71: error: ‘BigInt::BigInt(long unsigned int)’ previously defined here
BigInt.cpp: In member function ‘BigInt BigInt::inv(const BigInt&) const’:
BigInt.cpp:1411: warning: deprecated conversion from string constant to ‘char*’

can you fix it.

**Comment by JorjBauer** [comment]
Fixed in 1.0.3. Confirmed working on Debian 8 with primitives of 64-bit. Thanks for the report.
