### ISSUE TITLE
undefined symbol: __gxx_personality_v0

### ISSUE THREAD

**Issue by jamthief** [JorjBauer/lua-bigint#2]
I'm installing lua-bigint via luarocks and attempting to require it in NGINX in the normal way. When I do so, NGINX dumps out an error in the log:

```
2017/05/25 13:01:13 [error] 20#20: *43 lua entry thread aborted: runtime error: error loading module 'bigint' from file '/usr/local/lib/lua/5.1/bigint.so':
	/usr/local/lib/lua/5.1/bigint.so: undefined symbol: __gxx_personality_v0
stack traceback:
coroutine 0:
	[C]: in function 'require'
	[...snip...]
```

I can see in the output for `luarocks install bigint` that the library is being built locally using gcc:

```
$ luarocks install bigint
Warning: falling back to wget - install luasec to get native HTTPS support
BigInt.cpp: In member function 'BigInt BigInt::inv(const BigInt&) const':
BigInt.cpp:1411:12: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
    bi_p[0] = (const char *)"0";
            ^
BigInt.cpp:1447:10: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   bi_ret = (const char *)"0";
          ^
Installing https://rocks.moonscript.org/bigint-1.0.2-1.src.rock...
Using https://rocks.moonscript.org/bigint-1.0.2-1.src.rock... switching to 'build' mode
gcc -O2 -fPIC -I/usr/include/lua5.1 -c BigInt.cpp -o BigInt.o -DVERSION="1.02"
gcc -O2 -fPIC -I/usr/include/lua5.1 -c mainlib.c -o mainlib.o -DVERSION="1.02"
gcc -O2 -fPIC -I/usr/include/lua5.1 -c bigint-glue.cpp -o bigint-glue.o -DVERSION="1.02"
gcc -shared -o bigint.so -L/usr/local/lib BigInt.o mainlib.o bigint-glue.o
```

But I believe this last line might be the problem? Googling around for the gxx error message reveals [this stackoverflow post](https://stackoverflow.com/questions/203548/undefined-symbol-gxx-personality-v0-on-link) that suggests the object files should either be linked using `g++` instead, or `gcc` needs to be explicitly told about .cpp code using `-lstdc++`.

Environment:
```
Linux 4310fb9a2c0d 4.4.66-boot2docker x86_64 GNU/Linux
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
nginx version: nginx/1.10.3
gcc version 4.9.2 (Debian 4.9.2-10)
```

**Comment by AxelWal** [comment]
Same Problem here. With luarocks install bigint CC=g++ LD=g++ it uses g++ for build, but i have still the same error.
/usr/local/lib/lua/5.1/bigint.so: undefined symbol: _Z10bigint_newP9lua_State

**Comment by JorjBauer** [comment]
luarocks isn't particularly good at C++. I've added some hints to the readme about how to work around it on various platforms. Hopefully one of them solves the problem for you while we're waiting for a stable cross-platform cpp build system in luarocks...
